# Generated by Django 3.1.5 on 2021-01-16 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('session_status', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive'), ('finished', 'finished'), ('cancelled', 'cancelled')], default='active', max_length=20, verbose_name='Session Status')),
                ('session_type', models.CharField(choices=[('weekly', 'weekly'), ('one_day', 'one_day')], max_length=20, verbose_name='Session Type')),
                ('doctor_acceptance', models.BooleanField(verbose_name='D')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('session_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_sessions', to=settings.AUTH_USER_MODEL)),
                ('session_patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Session',
                'verbose_name_plural': 'Doctor Sessions',
                'ordering': ('-date',),
            },
        ),
    ]
